include:
  - '/.ci/gitlab/publish.yml'
  - '/.ci/gitlab/tests.yml'

stages:
  - build
  # TODO: add test stage to prevent cache throwouts if test failed?
  - publish

# Haddock, doctests, unittests, clash-dev testing. These are single threaded
# tests and therefore suitable for public runners.
tests-8.4.4:
  extends: .tests-interruptible
tests-8.8.4:
  extends: .tests-interruptible
tests-8.10.2:
  extends: .tests-interruptible
tests-8.6.5-singular-hidden:
  extends: .tests-interruptible
  variables:
    MULTIPLE_HIDDEN: "no"

# Testsuite (HDL generation and simulation). Highly parallel and memory
# intensive, should only picked up by beefy (local) runners.
testsuite-8.4.4:
  extends: .testsuite-interruptible
testsuite-8.8.4:
  extends: .testsuite-interruptible
testsuite-8.10.2:
  extends: .testsuite-interruptible
testsuite-8.6.5-singular-hidden:
  extends: .testsuite-interruptible
  variables:
    MULTIPLE_HIDDEN: "no"

# Tests on master. These are marked non-interruptible so we can receive e-mails
# on failed jobs, without receiving false negatives.
ghc-8.4.4-master:
  extends: .tests-non-interruptible
ghc-8.8.4-master:
  extends: .tests-non-interruptible
ghc-8.10.2-master:
  extends: .tests-non-interruptible
ghc-8.6.5-singular-hidden-master:
  extends: .tests-non-interruptible
  variables:
    MULTIPLE_HIDDEN: "no"

# "Publish" a release candidate
hackage-release-candidate:
  extends: .hackage

  variables:
    HACKAGE_RELEASE: "no"

  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "trigger"

# Release new version of Clash to Hackage
hackage-release:
  extends: .hackage

  variables:
    HACKAGE_RELEASE: "yes"

  rules:
    - if: '$CI_COMMIT_TAG != null' # tags

# Publish a release candidate (beta/edge) to snapcraft.io/clash
snap-beta-or-edge:
  extends: .snap
  variables:
    RELEASE_CHANNEL: beta_or_edge
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "trigger"

# Publish a new version to stable channel on snapcraft.io/clash
snap-stable:
  extends: .snap
  variables:
    RELEASE_CHANNEL: stable
  rules:
    - if: '$CI_COMMIT_TAG != null' # tags
