resolver: lts-18.24

packages:
- clash-prelude
- clash-lib
- clash-ghc
- clash-cores
- tests

extra-deps:
- ./clash-cosim
- attoparsec-aeson-2.1.0.0@sha256:fa83aba43bfa58490de8f274d19b9d58b6403a207b12cac5f93922102b084c52,1154
