resolver: lts-13.3

packages:
- clash-prelude
- clash-lib
- clash-ghc
# - testsuite # still uses cabal new-build internally

extra-deps:
- ./clash-cosim

- git: https://github.com/clash-lang/ghc-typelits-extra
  commit: a8de0b68b8216411cb862195354f251cd41bae50
