resolver: lts-19.25

ghc-options:
  "$locals": -Wall -Wcompat

packages:
- clash-prelude
- clash-lib
- clash-ghc
- clash-cores
- tests

extra-deps:
- ./clash-cosim
- prettyprinter-interp-0.2.0.0@sha256:45299b61bd6c27d594c1a72b5a8dd5734e791a59828725e4f4e420f3cc37232b,2016
